//Console.WriteLine("Enter meter: ");
//Console.WriteLine($"{int.Parse(Console.ReadLine()) * 100} centimeter");
//Console.WriteLine("Enter meter: ");
//Console.WriteLine($"{float.Parse(Console.ReadLine()) / 1000} kilometers");
//Console.WriteLine("Enter gramm: ");
//Console.WriteLine($"{float.Parse(Console.ReadLine()) / 1000} liters");
//Console.WriteLine("Enter liters: ");
//Console.WriteLine($"{float.Parse(Console.ReadLine()) / 3,785} gallons");
Console.WriteLine("Enter celsia: ");
Console.WriteLine($"{float.Parse(Console.ReadLine()) * (9/5) + 32} Farengeita");